site_name: Documentação - RudBee 
nav:
  - Home: index.md
  - Sobre o RudBee: about.md
  - Instalação: installation.md
  - Configuração das Dependências - GenB: configuration.md
  - Criação, Validação e Login de Usuários no RudBee: user.md
  - Criação de Bases e Formulários: base-and-form.md
theme:
  name: material
  language: pt
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  font:
    text: Inter
    code: Fira Code
  # favicon: assets/images/favicon.ico
  # logo: assets/images/logo.png
extra_css:
  - assets/styles/extra.css
extra:
  social:
    - icon: fontawesome/brands/github